### ISSUE TITLE
Issue after 2.30 upgrade

### ISSUE THREAD

**Issue by sHiKoRa** [MarvinSchenkel/HomeyKodi#17]
After the upgrade from 2.2.0 to 2.3.0 the app kept on crashing even after a Homey rebooted. Deleted the app and installed the app again, now Homey is not able to add the Kodi devices with error "invalid_capability"

**Comment by MarvinSchenkel** [comment]
The new app uses functionality of Homey that’s only available in v2 and up, which is why the app is crashing on 1.5.13. I can’t keep supporting ‘old’ firmwares of Homey. which is why I always make sure my app is compatible with the latest stable firmware (which is 2.0 at this time).

Your options are:
* Upgrade to Homey v2
* (if your tech savvy): Manually install the code from the PreV2Support branch: https://github.com/MarvinSchenkel/HomeyKodi/tree/PreV2Support
