### ISSUE TITLE
No triggers based on Kodi events

### ISSUE THREAD

**Issue by sossienl** [MarvinSchenkel/HomeyKodi#2]
I have installed the plugin and configured it with my Kodi instance. In Kodi it mentions that a listener is detected. So it seems to be correct.

After configuring a simple flow in Homey based on pausing a video in Kodi, nothing happens. I also created a flow that's triggered when I resume watching in Kodi. This also doesn't work. Because there is no other way to check what's going wrong I assume it has something to do with the app itself, but I might (hopefully) be wrong!

I'm on Homey Firmware Version: 0.8.29.
If you need any info, please let me know. I'm really looking forward to use this app.

**Comment by MarvinSchenkel** [comment]
Good to hear you're using this app! :). Flows are not triggered anymore because of a change as of 0.8.27. I already fixed this in v1.1, which is currently awaiting approval to be published in the app-store. If you really can't wait (and are a bit of a techy user), you can download the source code for v1.1 from Github and install it yourself through the command line. Check the forum for further instructions!

**Comment by sossienl** [comment]
I have updated manually. It's working. I do see some other stuff that is not working as expected. I'll create a new issue
