### ISSUE TITLE
Events triggering on unexpected moments

### ISSUE THREAD

**Issue by sossienl** [MarvinSchenkel/HomeyKodi#3]
I have updated to version 1.1 (manually) and I've tested several events for triggering a flow in Homey.
It seems to work, however I see some unexpected behaviour.

In Homey, I've created a new Flow that triggers a Push notification. The "Als" is set to "Een aflevering begint". I receive a notification when I start a random episode. So that's good. However, my setup in Kodi pauses the episode if it doesn't find a Dutch subtitle and suggests available online subs. When I close this and continue to watch the episode. I receive a 2nd notification, which means the flow is triggered again. However I would expect that "Een aflevering begint" is an **initial** event and is only triggered when I select an episode in Kodi to play. 

It's only when this subtitle stuff is shown. Maybe it's something you cannot catch when receiving the event from Kodi. In that case I need to think about a different approach.

**Comment by MarvinSchenkel** [comment]
This works as designed :). I will try to explain what's happening.

Kodi does not throw events like 'An episode starts', but only an event 'something starts playing', whenever that's a movie or an episode you started, or just a 'play action' after you paused your movie for a bit to get a new beer ;-).

In order to be able to implement an 'on resume' trigger, I check whether the movie or episode is at more than 0.1%, then it triggers an 'on resume', else an 'on movie/episode start'.

I am assuming that your subtitle stuff instantly pops up when you start a movie. The movie will be at less than 0.1% and thus the 'on movie start' event is fired instead of the 'on resume' event.

I'd have to come up with a differnt approach to distinguish start / resume events to fix this for you.

**Comment by sossienl** [comment]
Thanks! Makes sense.
